### PR TITLE
feat: Add the isWebHashHistory parameter to enable vue-router to use hash mode

### PR DESCRIPTION
**Pull request by 0ahz**
Add the `isWebHashHistory` parameter to enable `vue-router` to use `hash mode`.
```ts
// examples/multiple-pages/src/main.ts
export const createApp = ViteSSG(App, { isWebHashHistory: true, routes })
```

### CODE REVIEW

**Comment by antfu** [comment]
I think it's better to have

```ts
{
  mode: 'history' // 'hash'
}
```

WDYT?

**Comment by antfu** [comment]
I am also curious about how would you get SSG and hash mode working?

**Comment by 0ahz** [comment]
Build into a static page to deploy to `github-page`

**Comment by antfu** [comment]
I mean, in hash mode, the entry is all the same (index.html) and there is actually no need for SSG. History mode should work for GitHub Pages as well.

**Comment by 0ahz** [comment]
👌 I got it, thanks.

**Pull request closed without merging**
