### PR TITLE
fix: pass mode to vite build

### PR DESCRIPTION
**Pull request by Ti-webdev**

### CODE REVIEW

**Comment by hannoeru** [comment]
I don't think we need to do that, you can set mode in `vite.config.ts`.
@antfu WDYT?

**Comment by antfu** [comment]
@Ti-webdev Can you provide more context about what problem you are trying to fix here?

**Comment by Ti-webdev** [comment]
> @Ti-webdev Can you provide more context about what problem you are trying to fix here?

I prepared two versions for deploy: public and debug
It allows me switch to debug version on prod.

define mode in vite.config.ts works for me:
```
defineConfig({
   mode: process.env.MODE || process.env.NODE_ENV || 'development',
   ...
})
```

**Comment by antfu** [comment]
Looks like this issue is resolved for you. Closing now, thanks for your contributions.

**Pull request closed without merging**
